---
- name: Copy aliases
  copy:
    src: aliases
    dest: ~/.aliases
  become: 'yes'
  become_user: '{{ item }}'

- name: Enable aliases
  lineinfile:
    path: ~/.zshrc
    line: source $HOME/.aliases
    state: present
  become: 'yes'
  become_user: '{{ item }}'
