---
- name: Set zsh as default interpreter
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh

- include_tasks: oh_my_zsh.yml
- include_tasks: fzf.yml
- include_tasks: navi.yml
- include_tasks: meslo_font.yml
- include_tasks: powerlevel10k.yml
- include_tasks: autosuggestions.yml
- include_tasks: syntax_highlighting.yml
- include_tasks: aliases.yml

- name: Enable plugins
  lineinfile:
    path: ~/.zshrc
    regexp: "^plugins="
    line: "plugins=({{ zsh_plugins | join(' ') }})"
    state: present
  become: "yes"
  become_user: "{{ item }}"

- name: Copy zsh functions
  copy:
    src: g.zsh
    dest: ~/.oh-my-zsh/custom/g.zsh
  become: "yes"
  become_user: "{{ item }}"

- name: Copy JWT functions
  copy:
    src: jwt.zsh
    dest: ~/.oh-my-zsh/custom/jwt.zsh
  become: "yes"
  become_user: "{{ item }}"

- name: Set NeoVim a EDITOR
  lineinfile:
    path: ~/.zshrc
    line: "export EDITOR=nvim"
    state: present
  become: "yes"
  become_user: "{{ item }}"

- name: Enable local/bin into PATH
  lineinfile:
    path: ~/.zshrc
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
  become: "yes"
  become_user: "{{ item }}"

- name: Enable using [] in command line (Rake)
  lineinfile:
    path: ~/.zshrc
    line: "unsetopt nomatch"
    state: present
  become: "yes"
  become_user: "{{ item }}"
