---
- name: Set zsh as default interpreter
  user:
    name: '{{ item }}'
    shell: /usr/bin/zsh

- include: oh_my_zsh.yml
- include: fzf.yml
- include: navi.yml
- include: meslo_font.yml
- include: powerlevel10k.yml
- include: autosuggestions.yml
- include: syntax_highlighting.yml
- include: aliases.yml

- name: Enable plugins
  lineinfile:
    path: ~/.zshrc
    regexp: '^plugins='
    line: "plugins=({{ zsh_plugins | join(' ') }})"
    state: present
  become: 'yes'
  become_user: '{{ item }}'

- name: Copy zsh functions
  copy:
    src: g.zsh
    dest: ~/.oh-my-zsh/custom/g.zsh
  become: 'yes'
  become_user: '{{ item }}'

- name: Copy JWT functions
  copy:
    src: jwt.zsh
    dest: ~/.oh-my-zsh/custom/jwt.zsh
  become: 'yes'
  become_user: '{{ item }}'

- name: Set NeoVim a EDITOR
  lineinfile:
    path: ~/.zshrc
    line: 'export EDITOR=nvim'
    state: present
  become: 'yes'
  become_user: '{{ item }}'

- name: Enable NVM support
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} NVM ANSIBLE BLOCK"
    block: |
      export NVM_DIR="$HOME/.nvm"
      # This loads nvm
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      # This loads nvm bash_completion
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  become: 'yes'
  become_user: '{{ item }}'
  when: nvm_installed | bool

- name: Enable Rbenv support
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} RBENV ANSIBLE BLOCK"
    block: |
      # Rbenv
      if [ -f "/etc/profile.d/rbenv.sh" ]; then
        source "/etc/profile.d/rbenv.sh"
      fi
      eval "$(rbenv init -)"
  become: 'yes'
  become_user: '{{ item }}'
  when: rbenv_installed | bool

- name: Enable local/bin into PATH
  lineinfile:
    path: ~/.zshrc
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
  become: 'yes'
  become_user: '{{ item }}'
