---
- name: Install zsh, git, wget, powerline
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - git
    - wget
  tags: zsh

- name: Install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf

- name: Install asdf plugins
  command: "asdf plugin add {{ item }}"
  loop:
    - nodejs
    - ruby

- name: Install oh-my-zsh for users
  include_tasks: install_for_user.yml
  with_items: "{{ users }}"
  tags: zsh
