---
- name: Check if oh-my-zsh already installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_directory
  become: 'yes'
  become_user: '{{ item }}'

- name: Cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    version: master
  when: not oh_my_zsh_directory.stat.exists
  become: 'yes'
  become_user: '{{ item }}'

- name: Creating new ~/.zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  become: 'yes'
  become_user: '{{ item }}'
