---
- name: Check if Powerlevel9k already installed
  stat:
    path: ~/.oh-my-zsh/custom/themes/powerlevel9k
  register: powerline9k_directory
  become_user: '{{ item }}'

- name: Install PowerLevel9k theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
  when: not powerline9k_directory.stat.exists
  become_user: '{{ item }}'

- name: Set Powerline9k as zsh theme
  lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="powerlevel9k/powerlevel9k"'
    state: present
  become_user: '{{ item }}'
