---
- name: Check if syntax highlighting already installed
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  register: syntax_highlighting_directory
  become: 'yes'
  become_user: '{{ item }}'

- name: Install syntax highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    version: 0.6.0
  when: not syntax_highlighting_directory.stat.exists
  become: 'yes'
  become_user: '{{ item }}'
